bf16: true
cutoff_len: 2048
dataset: huatuo_dpo
dataset_dir: /data/home/yihui/LLM/Medical-LLM/dataset/data
ddp_timeout: 180000000
deepspeed: llamaboard_cache/ds_z3_config.json
do_train: true
enable_thinking: false
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 4
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /data/home/yihui/LLM/qwen3-32B
num_train_epochs: 3.0
optim: adamw_torch
output_dir: /data/home/yihui/LLM/Medical-LLM/weights/dpo-train_2025-12-29-18-00-39
packing: false
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
plot_loss: true
pref_beta: 0.1
pref_ftx: 0
pref_loss: sigmoid
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: dpo
swanlab_mode: cloud
swanlab_project: Medical-LLM
swanlab_run_name: sft-dpo
template: qwen3_nothink
trust_remote_code: true
use_swanlab: true
val_size: 0.01
warmup_steps: 100
