bf16: true
cutoff_len: 2048
dataset: huatuo_train
dataset_dir: Medical-LLM/dataset/data
ddp_timeout: 180000000
deepspeed: llamaboard_cache/ds_z2_config.json
do_train: true
enable_thinking: false
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: qwen3-32B
num_train_epochs: 3.0
optim: adamw_torch
output_dir: Medical-LLM/weights/train_sft_2025-12-19-11-22-35
packing: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
swanlab_mode: cloud
swanlab_project: Medical-LLM
swanlab_run_name: lora-sft
template: qwen3
trust_remote_code: true
use_swanlab: true
val_size: 0.01
warmup_steps: 100
